version: "3.8"
services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: make start
    restart: always

  db:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - ./data-db:/var/lib/postgresql/data
    env_file:
      - .env