version: "3.8"
networks:
  app-network:
    driver: bridge
services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: make start
    restart: always
    networks:
      - app-network


  db:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - ./data-db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app-network

  script:
    build:
      context: .
    container_name: script
    depends_on:
      - db
    env_file:
      - .env
    command: make script
    restart: always
    networks:
      - app-network